name: installcheck
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        PG:
          - 11
          - 10
          - 9.6
          - 9.5
          - 9.4
          - 9.3
    env:
      PG_CPPFLAGS: -fprofile-arcs -ftest-coverage -O0
      SHLIB_LINK: -lgcov
    steps:
      - uses: actions/checkout@v2
      - run: >-
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/
          $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      - run: >-
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc |
          sudo apt-key add -
      - run: PGPORT=5440
      - run: sudo /etc/init.d/postgresql stop
      - run: sudo apt-get remove -y postgresql-9.2
      - run: >-
          sudo apt-get -o
          Dir::Etc::sourcelist="/etc/apt/sources.list.d/pgdg.list" -o
          Dir::Etc::sourceparts='-' -o APT::Get::List-Cleanup='0' update
      - run: sudo apt-get install postgresql-${{ matrix.PG }} postgresql-server-dev-${{ matrix.PG }} acl
      - run: sudo pg_createcluster -p $PGPORT ${{ matrix.PG }} test
      - run: >-
          sudo sed -i '1i local all all trust'
          /etc/postgresql/${{ matrix.PG }}/test/pg_hba.conf
      - run: 'setfacl -Rm u:postgres:rwx,d:u:travis:rwx $HOME'
      - run: sudo /etc/init.d/postgresql start ${{ matrix.PG }}
      - run: psql -p $PGPORT -U postgres postgres -xA -c 'select version()'
      - run: make
      - run: sudo make install
      - run: >-
          make installcheck PGUSER=postgres PGPORT=$PGPORT || (cat
          regression.diffs && false)
